export const endpoints = {
  drills: 'drills',
  drill: 'drill',
  createDrill: 'drill/create',
  updateDrill: 'drill/update/',
  deleteDrill: 'drill/delete/',
  screws: 'screws',
  screw: 'screw',
  plates: 'plates',
  plate: 'plate',
  archive_drills: 'archive_drills',
  archive_drill: 'archive_drill',
  register: 'auth/register',
  login: 'auth/jwt/login',
}
