export const endpoints = {
  drills: 'drills',
  drill: 'drill',
  createDrill: 'drill/create',
  updateDrill: 'drill/update/',
  deleteDrill: 'drill/delete/',
  archive_drills: 'archive_drills',
  archive_drill: 'archive_drill',
  screws: 'screws',
  screw: 'screw',
  createScrew: 'screw/create',
  updateScrew: 'screw/update/',
  deleteScrew: 'screw/delete/',
  plates: 'plates',
  plate: 'plate',
  createPlate: 'plate/create',
  updatePlate: 'plate/update/',
  deletePlate: 'plate/delete/',
  register: 'auth/register',
  login: 'auth/jwt/login',
}
